### ISSUE TITLE
Can you add a LICENSE file?

### ISSUE THREAD

**Issue by edwinhere** [aviaviavi/legion#1]
Please add a license file so that people know if they can use or contribute.

**Comment by aviaviavi** [comment]
Definitely, thanks for opening the issue. I'll get one in shortly. I'd be thrilled to have people using this and contributing!

**Comment by aviaviavi** [comment]
Done. I'm happy to take any PR's, discuss changes, etc

**Comment by edwinhere** [comment]
Will do. Thanks.
